function nf_validate_development_feedback_audit(Audit, Trial, RTConfig, Modes)
% NF_VALIDATE_DEVELOPMENT_FEEDBACK_AUDIT Validate complete Step 0 flip evidence.

requiredAudit = {'DisplayMode','Backend','DevelopmentDisplay', ...
    'UsesRealPsychtoolbox','UsesHeadlessPsychtoolboxTest','ScreenNumber', ...
    'AvailableScreens','WindowRect','NFlipRequests','NCompletedFlips', ...
    'NMissedFlips','FlipAudit','LatencyMeanMs','LatencyMedianMs', ...
    'LatencyP95Ms','LatencyConfiguredPercentileMs','LatencyMaxMs', ...
    'LatencyPercentile','LatencyValuesMs'};
if ~isstruct(Audit) || ~isscalar(Audit) || ...
        ~all(isfield(Audit, requiredAudit)) || ...
        ~strcmp(Audit.Backend, Modes.FeedbackBackend.Psychtoolbox) || ...
        ~Audit.DevelopmentDisplay
    local_error('Step 0 feedback audit is incomplete or not Psychtoolbox development feedback.');
end

requiredTrial = {'FirstTrialSample','LastTrialSample', ...
    'FirstValidMeasureWindowEndSample','NValidMeasures', ...
    'FeedbackLatencyPercentile','FeedbackLatencyConfiguredPercentileMs', ...
    'FeedbackLatencyMsP95','FeedbackLatencyMsValues'};
if ~isstruct(Trial) || ~isscalar(Trial) || ...
        ~all(isfield(Trial, requiredTrial)) || ...
        ~local_is_positive_integer_scalar(Trial.FirstTrialSample) || ...
        ~local_is_positive_integer_scalar(Trial.LastTrialSample) || ...
        Trial.LastTrialSample < Trial.FirstTrialSample || ...
        ~local_is_positive_integer_scalar(Trial.FirstValidMeasureWindowEndSample) || ...
        Trial.FirstValidMeasureWindowEndSample > Trial.LastTrialSample || ...
        ~local_is_positive_integer_scalar(Trial.NValidMeasures)
    local_error('Step 0 trial bounds are incomplete or invalid.');
end

isReal = strcmp(RTConfig.DevelopmentSession.DisplayMode, ...
    Modes.DevelopmentDisplay.RealPsychtoolbox);
if Audit.UsesRealPsychtoolbox ~= isReal || ...
        Audit.UsesHeadlessPsychtoolboxTest == isReal || ...
        ~isfinite(Audit.ScreenNumber) || ...
        ~ismember(Audit.ScreenNumber, Audit.AvailableScreens) || ...
        ~isnumeric(Audit.WindowRect) || numel(Audit.WindowRect) ~= 4 || ...
        any(~isfinite(Audit.WindowRect))
    local_error('Step 0 feedback display identity or geometry is invalid.');
end

requiredFlip = {'RequestIssuedAt','RequestedWhen','VBLTimestamp', ...
    'StimulusOnsetTime','FlipTimestamp','Missed','DeadlineMissed', ...
    'BeamPosition','MeasureTime','WindowStartSample','WindowEndSample', ...
    'ValidMeasureIndex'};
if ~isstruct(Audit.FlipAudit) || ...
        ~local_is_nonnegative_integer_scalar(Audit.NFlipRequests) || ...
        ~local_is_nonnegative_integer_scalar(Audit.NCompletedFlips) || ...
        ~local_is_nonnegative_integer_scalar(Audit.NMissedFlips) || ...
        Audit.NFlipRequests < 1 || Audit.NCompletedFlips < 1 || ...
        Audit.NCompletedFlips > Audit.NFlipRequests || ...
        Audit.NMissedFlips > Audit.NFlipRequests || ...
        Audit.NFlipRequests ~= numel(Audit.FlipAudit) || ...
        ~all(isfield(Audit.FlipAudit, requiredFlip))
    local_error('Step 0 feedback audit does not contain a completed flip.');
end

expectedFlipWhen = RTConfig.DevelopmentSession.Feedback.FlipWhen;
expectedWindowSamples = RTConfig.PowerWindowSamples;
rawMissed = zeros(1, numel(Audit.FlipAudit));
deadlineMissed = false(1, numel(Audit.FlipAudit));
completed = false(1, numel(Audit.FlipAudit));
orderedFields = {'RequestIssuedAt','VBLTimestamp','StimulusOnsetTime', ...
    'FlipTimestamp','MeasureTime','WindowStartSample','WindowEndSample', ...
    'ValidMeasureIndex'};
previous = struct();
for iFlip = 1:numel(Audit.FlipAudit)
    flip = Audit.FlipAudit(iFlip);
    if ~local_is_finite_numeric_scalar(flip.RequestedWhen) || ...
            flip.RequestedWhen ~= expectedFlipWhen
        local_error('Step 0 flip request timing does not match configured FlipWhen.');
    end
    if ~local_is_finite_numeric_scalar(flip.Missed)
        local_error(['Step 0 Psychtoolbox missed deadline estimate must be a ' ...
            'finite, real, numeric scalar.']);
    end
    expectedMissed = flip.Missed > 0;
    if ~islogical(flip.DeadlineMissed) || ...
            ~isscalar(flip.DeadlineMissed) || ...
            flip.DeadlineMissed ~= expectedMissed
        local_error(['Step 0 DeadlineMissed does not match the signed ' ...
            'missed deadline estimate.']);
    end

    timestampFields = {'RequestIssuedAt','VBLTimestamp', ...
        'StimulusOnsetTime','FlipTimestamp','MeasureTime'};
    if any(~cellfun(@(name) local_is_finite_numeric_scalar(flip.(name)), ...
            timestampFields)) || ...
            ~local_is_finite_numeric_scalar(flip.BeamPosition)
        local_error('Step 0 flip timestamps or beam-position metadata are invalid.');
    end
    if ~local_is_positive_integer_scalar(flip.WindowStartSample) || ...
            ~local_is_positive_integer_scalar(flip.WindowEndSample) || ...
            flip.WindowEndSample < flip.WindowStartSample || ...
            ~local_is_positive_integer_scalar(flip.ValidMeasureIndex)
        local_error('Step 0 flip sample-window or measure-index metadata are invalid.');
    end
    if flip.WindowEndSample - flip.WindowStartSample + 1 ~= expectedWindowSamples
        local_error('Step 0 feedback flip window length does not match PowerWindowSamples.');
    end
    if flip.ValidMeasureIndex > Trial.NValidMeasures
        local_error('Step 0 feedback flip measure index exceeds the trial valid-measure count.');
    end
    if flip.WindowStartSample < Trial.FirstTrialSample || ...
            flip.WindowEndSample < Trial.FirstValidMeasureWindowEndSample
        local_error('Step 0 feedback flip contains transition or pre-warm-up samples.');
    end
    if flip.WindowEndSample > Trial.LastTrialSample
        local_error('Step 0 feedback flip extends beyond the final processed trial sample.');
    end
    if iFlip > 1
        for iField = 1:numel(orderedFields)
            fieldName = orderedFields{iField};
            if flip.(fieldName) < previous.(fieldName)
                local_error('Step 0 flip metadata are not nondecreasing in presentation order.');
            end
        end
    end
    rawMissed(iFlip) = flip.Missed;
    deadlineMissed(iFlip) = flip.DeadlineMissed;
    completed(iFlip) = local_flip_is_complete(flip);
    previous = flip;
end

if Audit.NMissedFlips ~= nnz(rawMissed > 0) || ...
        Audit.NMissedFlips ~= nnz(deadlineMissed)
    local_error('Step 0 missed-flip count does not match flip audit entries.');
end
if nnz(completed) ~= Audit.NCompletedFlips
    local_error('Step 0 completed-flip count does not match finite flip timestamps.');
end

firstFlip = Audit.FlipAudit(find(completed, 1, 'first'));
if firstFlip.WindowStartSample < Trial.FirstTrialSample || ...
        firstFlip.WindowEndSample < Trial.FirstValidMeasureWindowEndSample || ...
        firstFlip.WindowEndSample > Trial.LastTrialSample || ...
        firstFlip.ValidMeasureIndex > Trial.NValidMeasures
    local_error('First feedback flip was not driven by a fresh valid trial window.');
end

latency = [Audit.LatencyMeanMs Audit.LatencyMedianMs ...
    Audit.LatencyP95Ms Audit.LatencyConfiguredPercentileMs Audit.LatencyMaxMs];
latencyValues = Audit.LatencyValuesMs;
if ~local_is_finite_numeric_scalar(Audit.LatencyPercentile) || ...
        Audit.LatencyPercentile ~= RTConfig.Feedback.LatencySummary.Percentile || ...
        ~isnumeric(latencyValues) || isempty(latencyValues) || ...
        any(~isfinite(latencyValues(:))) || any(latencyValues(:) < 0) || ...
        any(~isfinite(latency)) || any(latency < 0) || ...
        Audit.LatencyMaxMs < Audit.LatencyMeanMs || ...
        Audit.LatencyP95Ms > Audit.LatencyMaxMs
    local_error('Step 0 feedback latency summary is inconsistent.');
end
expectedPercentile = local_percentile(sort(latencyValues(:)), ...
    RTConfig.Feedback.LatencySummary.Percentile);
expectedP95 = local_true_p95(sort(latencyValues(:)));
if Audit.LatencyConfiguredPercentileMs ~= expectedPercentile || ...
        Audit.LatencyP95Ms ~= expectedP95 || ...
        Trial.FeedbackLatencyPercentile ~= Audit.LatencyPercentile || ...
        Trial.FeedbackLatencyConfiguredPercentileMs ~= expectedPercentile || ...
        ~isequal(Trial.FeedbackLatencyMsValues(:), latencyValues(:)) || ...
        Trial.FeedbackLatencyMsP95 ~= expectedP95
    local_error('Step 0 configured latency percentile was not propagated consistently.');
end
end

function tf = local_flip_is_complete(flip)
fields = {'VBLTimestamp','StimulusOnsetTime','FlipTimestamp'};
tf = all(isfield(flip, fields));
if ~tf
    return;
end
for iField = 1:numel(fields)
    tf = tf && local_is_finite_numeric_scalar(flip.(fields{iField}));
end
end

function tf = local_is_nonnegative_integer_scalar(value)
tf = isnumeric(value) && isscalar(value) && isreal(value) && ...
    isfinite(value) && value >= 0 && value == round(value);
end

function tf = local_is_finite_numeric_scalar(value)
tf = isnumeric(value) && isscalar(value) && isreal(value) && isfinite(value);
end

function tf = local_is_positive_integer_scalar(value)
tf = local_is_nonnegative_integer_scalar(value) && value >= 1;
end

function value = local_true_p95(values)
% Latency fields labeled P95 always retain true 95th-percentile semantics.
value = local_percentile(values, 95);
end

function value = local_percentile(values, pct)
if numel(values) == 1
    value = values(1);
    return;
end
% Convert the configured percentage to a unit interpolation fraction.
position = 1 + (pct ./ 100) .* (numel(values) - 1);
lowerIndex = floor(position);
upperIndex = ceil(position);
if lowerIndex == upperIndex
    value = values(lowerIndex);
else
    value = values(lowerIndex) .* (upperIndex - position) + ...
        values(upperIndex) .* (position - lowerIndex);
end
end

function local_error(message)
error('neurofeedback:developmentFeedbackAuditInvalid', '%s', message);
end
