function run_all_tests()
% RUN_ALL_TESTS Run first-version neurofeedback_rt tests.
%
% USAGE:  run_all_tests()
%
% DESCRIPTION:
%     Adds the project to the MATLAB path, runs each named test function,
%     prints pass/fail status, and raises an error if any test fails.

%% ===== ADD PROJECT PATHS =====
% Ensure tests can call project functions from a fresh MATLAB session.
projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(projectRoot);
nf_add_paths();

%% ===== DEFINE TEST LIST =====
% Keep the execution order explicit for reproducible failures.
tests = { ...
    'test_brainstorm_intro_validation_config', ...
    'test_brainstorm_intro_validation_config_enables_bst_function', ...
    'test_analysis_config_defaults', ...
    'test_modes_constants', ...
    'test_project_root_helper', ...
    'test_session_requires_spatial', ...
    'test_live_config_defaults', ...
    'test_mock_live_test_config_defaults', ...
    'test_live_timing_defaults', ...
    'test_live_fieldtrip_timing_has_no_escape_hatch', ...
    'test_mock_live_uses_same_timing_assertions_as_live', ...
    'test_trial_failsafe_single_source_of_truth', ...
    'test_acquisition_only_sessions_do_not_require_combined_matrix_path', ...
    'test_acquisition_only_sessions_do_not_force_require_ctf_res4', ...
    'test_spatial_sessions_require_precomputed_path_if_precomputed', ...
    'test_require_ctf_res4_logic_by_matrix_source', ...
    'test_check_config_live_fields_without_acquisition', ...
    'test_check_config_handles_unfinalized_live_config', ...
    'test_check_config_uses_internal_finalized_flag', ...
    'test_live_config_has_single_connection_settings', ...
    'test_live_config_grep_historical_host_port_dependencies', ...
    'test_live_config_requires_host_port_for_real_buffer', ...
    'test_live_add_fieldtrip_paths_uses_test_hook_without_buffer', ...
    'test_live_add_fieldtrip_paths_missing_buffer_errors', ...
    'test_live_detect_buffer_shadowing_helper', ...
    'test_live_add_fieldtrip_paths_detects_buffer_shadowing', ...
    'test_live_add_fieldtrip_paths_adds_fieldtriproot_subfolders', ...
    'test_live_read_header_fieldtrip_fake_buffer', ...
    'test_live_read_header_rejects_fs_mismatch', ...
    'test_live_ctf_res4_missing_allowed_when_not_required', ...
    'test_live_ctf_res4_missing_errors_when_required', ...
    'test_live_detect_acq_block_size_fake_advance', ...
    'test_live_source_init_fake_header_sets_cursor', ...
    'test_live_get_chunk_ben_indexing_fake_buffer', ...
    'test_source_dry_run_fake_header', ...
    'test_live_channel_check_report_schema', ...
    'test_save_live_channel_check_requires_existing_session', ...
    'test_live_channel_check_acquisition_only_no_combined_matrix_required', ...
    'test_live_channel_check_fails_gracefully_when_buffer_missing', ...
    'test_live_channel_check_rethrows_if_report_save_fails', ...
    'test_live_source_init_allows_empty_data_for_live_only', ...
    'test_live_source_dispatch_preserves_simulated_modes', ...
    'test_live_chunk_smoke_test_fake_buffer_passes', ...
    'test_live_chunk_smoke_test_detects_sample_gap', ...
    'test_live_chunk_smoke_test_rejects_wrong_chunk_size', ...
    'test_live_chunk_smoke_test_detects_channel_count_change', ...
    'test_live_chunk_smoke_test_acquisition_only_no_combined_matrix_required', ...
    'test_live_chunk_smoke_test_does_not_call_rt_core', ...
    'test_save_live_chunk_smoke_test_report_schema', ...
    'test_safety_live_chunk_smoke_test_phase', ...
    'test_live_rt_dry_run_fake_buffer_technical_fallback_passes', ...
    'test_live_rt_dry_run_requires_spatial_for_precomputed_empty_path', ...
    'test_live_rt_dry_run_uses_combined_matrix_contract', ...
    'test_live_rt_dry_run_calls_rt_core_but_not_feedback', ...
    'test_live_rt_dry_run_valid_measures_after_warmup', ...
    'test_live_rt_dry_run_feedback_fields_remain_unmapped', ...
    'test_live_rt_dry_run_no_baseline_zscore_by_default', ...
    'test_save_live_rt_dry_run_report_schema', ...
    'test_safety_live_rt_dry_run_phase', ...
    'test_prepare_live_combined_matrix_technical_fallback_contract', ...
    'test_prepare_live_combined_matrix_compute_live_errors', ...
    'test_revalidate_live_spatial_against_source_rejects_mismatch', ...
    'test_live_rt_dry_run_real_buffer_path_not_replaced_by_test_hook', ...
    'test_live_rt_dry_run_source_uses_public_dispatchers', ...
    'test_finalize_config_is_idempotent', ...
    'test_synthetic_theta_dataset', ...
    'test_measures_to_table', ...
    'test_baseline_to_table', ...
    'test_validation_to_table', ...
    'test_synthetic_theta_recovery', ...
    'test_wrong_band_control_rejected', ...
    'test_trial_report_generation', ...
    'test_validation_report_generation', ...
    'test_synthetic_input_report_generation', ...
    'test_marc_validation_report_generation', ...
    'test_marc_report_includes_synthetic_input_metadata', ...
    'test_marc_validation_bundle_smoke', ...
    'test_offline_reference_stepped_matches_dense', ...
    'test_band_detection_synthetic_positive', ...
    'test_band_detection_wrong_band_control', ...
    'test_deterministic_dropped_chunk_simulation', ...
    'test_validate_dropped_chunk_behavior', ...
    'test_filter_empirical_delay_config_propagates_to_measure', ...
    'test_config_hash_changes_with_target_band', ...
    'test_config_hash_changes_with_drop_schedule', ...
    'test_config_hash_changes_with_expected_channel_names', ...
    'test_baseline_accumulation_and_finalization', ...
    'test_baseline_finalize_preserves_audit_fields', ...
    'test_baseline_quality_rejects_poor_baseline', ...
    'test_load_baseline_rejects_poor_quality', ...
    'test_baseline_update_rejects_flagged_valid_measures', ...
    'test_zscore_computation_from_saved_baseline', ...
    'test_trial_log_saving_and_reloading', ...
    'test_config_hash_rejects_incompatible_baseline', ...
    'test_feedback_mapping_separated_from_rt_core', ...
    'test_measure_feedback_fields', ...
    'test_circle_feedback_mapping', ...
    'test_feedback_map_local_circle', ...
    'test_feedback_visual_alpha_one_no_extra_smoothing', ...
    'test_feedback_stays_outside_rt_core', ...
    'test_feedback_init_none_mode', ...
    'test_feedback_init_mock_debug_plot', ...
    'test_feedback_update_local_circle_debug_plot', ...
    'test_feedback_update_nan_radius_draws_background_only', ...
    'test_feedback_close_safe', ...
    'test_live_requires_psychtoolbox_unless_override', ...
    'test_feedback_update_does_not_remap_value', ...
    'test_feedback_display_does_not_touch_rt_core', ...
    'test_make_session_output_dir_unique', ...
    'test_logger_init_creates_session_tree', ...
    'test_logger_append_chunk_meta', ...
    'test_logger_append_measure', ...
    'test_save_partial_log_marks_partial', ...
    'test_save_partial_log_is_incremental', ...
    'test_logger_close_writes_files', ...
    'test_logger_close_idempotent', ...
    'test_logger_does_not_touch_rt_core', ...
    'test_fft_comparison_detects_injected_theta', ...
    'test_fft_comparison_sample_range_mapping', ...
    'test_iir_sos_comparison_self_reference', ...
    'test_brainstorm_missing_skips_cleanly', ...
    'test_brainstorm_iir_sos_bst_function_synthetic', ...
    'test_brainstorm_intro_real_iir_sos_comparison_if_available', ...
    'test_run_validation_segment_bounds_not_double_applied', ...
    'test_sync_diagnostics_returned', ...
    'test_time_equals_neural_time_with_delay', ...
    'test_source_segment_bounds', ...
    'test_buffer_gap_uses_tolerance', ...
    'test_filter_continuity_across_chunks', ...
    'test_buffer_wraparound', ...
    'test_buffer_getlast_before_full', ...
    'test_buffer_gap_detection', ...
    'test_measure_schema', ...
    'test_measure_timing_metadata', ...
    'test_zsmooth_state_update', ...
    'test_fs_mismatch_errors', ...
    'test_sos_gain_after_filter', ...
    'test_validation_alignment_uses_uncorrected_samples'};

%% ===== RUN TESTS =====
% Continue after failures so the summary includes every failing test.
nFailed = 0;
for iTest = 1:numel(tests)
    testName = tests{iTest};
    try
        feval(testName);
        fprintf('[PASS] %s\n', testName);
    catch ME
        nFailed = nFailed + 1;
        fprintf('[FAIL] %s: %s\n', testName, ME.message);
    end
end

%% ===== REPORT RESULTS =====
% Match MATLAB test helpers by throwing if any test failed.
if nFailed > 0
    error('%d test(s) failed.', nFailed);
end

fprintf('All %d tests passed.\n', numel(tests));

end
