function run_all_tests()
% RUN_ALL_TESTS Run first-version neurofeedback_rt tests.
%
% USAGE:  run_all_tests()
%
% DESCRIPTION:
%     Adds the project to the MATLAB path, runs each named test function,
%     prints pass/fail status, and raises an error if any test fails.

%% ===== ADD PROJECT PATHS =====
% Ensure tests can call project functions from a fresh MATLAB session.
projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(projectRoot);
nf_add_paths();

%% ===== DEFINE TEST LIST =====
% Keep the execution order explicit for reproducible failures.
tests = { ...
    'test_brainstorm_intro_validation_config', ...
    'test_offline_reference_stepped_matches_dense', ...
    'test_band_detection_synthetic_positive', ...
    'test_band_detection_wrong_band_control', ...
    'test_fft_comparison_detects_injected_theta', ...
    'test_fft_comparison_sample_range_mapping', ...
    'test_iir_sos_comparison_self_reference', ...
    'test_brainstorm_missing_skips_cleanly', ...
    'test_run_validation_segment_bounds_not_double_applied', ...
    'test_sync_diagnostics_returned', ...
    'test_time_equals_neural_time_with_delay', ...
    'test_source_segment_bounds', ...
    'test_buffer_gap_uses_tolerance', ...
    'test_filter_continuity_across_chunks', ...
    'test_buffer_wraparound', ...
    'test_buffer_getlast_before_full', ...
    'test_buffer_gap_detection', ...
    'test_measure_schema', ...
    'test_measure_timing_metadata', ...
    'test_zsmooth_state_update', ...
    'test_fs_mismatch_errors', ...
    'test_sos_gain_after_filter', ...
    'test_validation_alignment_uses_uncorrected_samples'};

%% ===== RUN TESTS =====
% Continue after failures so the summary includes every failing test.
nFailed = 0;
for iTest = 1:numel(tests)
    testName = tests{iTest};
    try
        feval(testName);
        fprintf('[PASS] %s\n', testName);
    catch ME
        nFailed = nFailed + 1;
        fprintf('[FAIL] %s: %s\n', testName, ME.message);
    end
end

%% ===== REPORT RESULTS =====
% Match MATLAB test helpers by throwing if any test failed.
if nFailed > 0
    error('%d test(s) failed.', nFailed);
end

fprintf('All %d tests passed.\n', numel(tests));

end
