function test_logger_does_not_touch_rt_core()
% TEST_LOGGER_DOES_NOT_TOUCH_RT_CORE Guard RT core boundaries.

%% ===== SCAN RT CORE =====
% Strip MATLAB comments so comments alone cannot trigger the guard.
rtCorePath = fullfile(nf_project_root(), 'rt', 'nf_rt_process_chunk.m');
sourceText = fileread(rtCorePath);
sourceText = regexprep(sourceText, '%[^\n\r]*', '');

blockedTokens = { ...
    'nf_logger_init', ...
    'nf_logger_append_chunk_meta', ...
    'nf_logger_append_measure', ...
    'nf_save_partial_log', ...
    'nf_logger_close', ...
    'nf_make_session_output_dir'};
for iToken = 1:numel(blockedTokens)
    assert(~contains(sourceText, blockedTokens{iToken}), ...
        'Logger token found in RT core: %s', blockedTokens{iToken});
end

end
