function test_feedback_display_does_not_touch_rt_core()
% TEST_FEEDBACK_DISPLAY_DOES_NOT_TOUCH_RT_CORE Guard RT core boundaries.

%% ===== SCAN RT CORE =====
% Strip MATLAB comments so comments alone cannot trigger the guard.
rtCorePath = fullfile(nf_project_root(), 'rt', 'nf_rt_process_chunk.m');
sourceText = fileread(rtCorePath);
sourceText = regexprep(sourceText, '%[^\n\r]*', '');

blockedTokens = { ...
    'nf_feedback_init', ...
    'nf_feedback_update', ...
    'nf_feedback_close', ...
    'Screen', ...
    'PsychImaging', ...
    'figure', ...
    'rectangle'};
for iToken = 1:numel(blockedTokens)
    assert(~contains(sourceText, blockedTokens{iToken}), ...
        'Feedback display token found in RT core: %s', blockedTokens{iToken});
end

end
