function test_brainstorm_intro_validation_config_enables_bst_function()
% TEST_BRAINSTORM_INTRO_VALIDATION_CONFIG_ENABLES_BST_FUNCTION Check overrides.

%% ===== CHECK DEFAULT REMAINS PORTABLE =====
% Default tutorial config must keep Brainstorm comparison skipped.
RTConfig = nf_brainstorm_intro_validation_config('fake_path.mat', 600, 274);
assert(strcmp(RTConfig.Validation.Step1.Brainstorm.Mode, 'skip'), ...
    'Default Brainstorm mode should remain skip.');
assert(RTConfig.Validation.Step1.Brainstorm.RequireForPass == false, ...
    'Default RequireForPass should remain false.');

%% ===== CHECK EXPLICIT BST_FUNCTION ENABLEMENT =====
% This test only checks config plumbing and does not require Brainstorm installed.
RTConfig = nf_brainstorm_intro_validation_config('fake_path.mat', 600, 274, [8 12], ...
    'BrainstormMode', 'bst_function', ...
    'RequireBrainstormForPass', true, ...
    'BrainstormPath', 'C:\Users\yango\Documents\brainstorm3', ...
    'FieldTripPath', 'C:\Users\yango\Documents\fieldtrip', ...
    'BrainstormMethod', 'bst-hfilter-2019');

assert(strcmp(RTConfig.Validation.Step1.Brainstorm.Mode, 'bst_function'), ...
    'BrainstormMode override failed.');
assert(RTConfig.Validation.Step1.Brainstorm.RequireForPass == true, ...
    'RequireBrainstormForPass override failed.');
assert(strcmp(RTConfig.Brainstorm.Path, 'C:\Users\yango\Documents\brainstorm3'), ...
    'BrainstormPath override failed.');
assert(strcmp(RTConfig.Brainstorm.FieldTripPath, 'C:\Users\yango\Documents\fieldtrip'), ...
    'FieldTripPath override failed.');
assert(strcmp(RTConfig.Brainstorm.OfflineBandpassFunction, 'bst_bandpass_hfilter'), ...
    'OfflineBandpassFunction default changed unexpectedly.');
assert(strcmp(RTConfig.Brainstorm.OfflineBandpassMethod, 'bst-hfilter-2019'), ...
    'BrainstormMethod override failed.');

end
