function tf = nf_session_requires_spatial(RTConfig)
% NF_SESSION_REQUIRES_SPATIAL True when a session needs spatial processing.

Modes = nf_modes();

spatialSessions = { ...
    Modes.Session.LiveRTDryRun, ...
    Modes.Session.LiveResting, ...
    Modes.Session.LiveTrial, ...
    Modes.Session.LiveSelfTest};

tf = isfield(RTConfig, 'Session') && ...
     isfield(RTConfig.Session, 'Mode') && ...
     any(strcmp(RTConfig.Session.Mode, spatialSessions));

end
