function SessionResult = nf_save_development_session_report(SessionResult, RTConfig)
% NF_SAVE_DEVELOPMENT_SESSION_REPORT Save Step 0 MAT and compact CSV reports.

output = RTConfig.DevelopmentSession.Output;
if SessionResult.Pass
    matName = output.SuccessMatFilename;
    csvName = output.SuccessCsvFilename;
else
    matName = output.PartialMatFilename;
    csvName = output.PartialCsvFilename;
end
SessionResult.SummaryPath = '';
SessionResult.SummaryCsvPath = '';
SessionResult.PartialReportPath = '';
SessionResult.PartialReportCsvPath = '';
matPath = fullfile(SessionResult.SessionOutputDir, matName);
csvPath = fullfile(SessionResult.SessionOutputDir, csvName);
if SessionResult.Pass
    SessionResult.SummaryPath = matPath;
    SessionResult.SummaryCsvPath = csvPath;
else
    SessionResult.PartialReportPath = matPath;
    SessionResult.PartialReportCsvPath = csvPath;
end

save(matPath, 'SessionResult', 'RTConfig');
missedEstimates = local_nested(SessionResult, ...
    {'FeedbackAudit','FlipAudit'}, struct([]));
if isstruct(missedEstimates) && isfield(missedEstimates, 'Missed')
    missedEstimates = [missedEstimates.Missed];
else
    missedEstimates = [];
end
cleanupMessages = local_field(SessionResult, 'CleanupMessages', {});
T = table({SessionResult.RunID}, {SessionResult.OverallStatus}, ...
    SessionResult.Pass, SessionResult.Completed, SessionResult.Partial, ...
    SessionResult.DevelopmentOnly, SessionResult.ProductionEquivalent, ...
    {SessionResult.CurrentPhase}, {SessionResult.StopReason}, ...
    SessionResult.DurationSeconds, {SessionResult.ErrorIdentifier}, ...
    {SessionResult.SessionOutputDir}, SessionResult.SourceReady, ...
    {local_nested_text(SessionResult, {'SpatialSummary','Hash'}, '')}, ...
    {local_field(SessionResult, 'BaselineConfigHash', '')}, ...
    {local_field(SessionResult, 'TrialBaselineConfigHash', '')}, ...
    local_nested_numeric(SessionResult, ...
        {'TrialResult','FeedbackLatencyPercentile'}, NaN), ...
    local_nested_numeric(SessionResult, ...
        {'TrialResult','FeedbackLatencyConfiguredPercentileMs'}, NaN), ...
    local_nested_numeric(SessionResult, ...
        {'TrialResult','FeedbackLatencyMsP95'}, NaN), ...
    local_nested_numeric(SessionResult, ...
        {'TransitionResult','SkippedFirstSample'}, NaN), ...
    local_nested_numeric(SessionResult, ...
        {'TransitionResult','SkippedLastSample'}, NaN), ...
    local_nested_numeric(SessionResult, ...
        {'TransitionResult','SkippedSampleCount'}, NaN), ...
    local_nested_numeric(SessionResult, ...
        {'TrialResult','FirstTrialSample'}, NaN), ...
    local_nested_numeric(SessionResult, ...
        {'TrialResult','LastTrialSample'}, NaN), ...
    local_nested_numeric(SessionResult, ...
        {'TrialResult','FirstValidMeasureWindowEndSample'}, NaN), ...
    local_nested_numeric(SessionResult, ...
        {'TrialResult','FirstFeedbackUpdateWindowEndSample'}, NaN), ...
    local_nested_numeric(SessionResult, ...
        {'FeedbackAudit','NFlipRequests'}, 0), ...
    local_nested_numeric(SessionResult, ...
        {'FeedbackAudit','NCompletedFlips'}, 0), ...
    local_nested_numeric(SessionResult, ...
        {'FeedbackAudit','NMissedFlips'}, 0), ...
    {local_numeric_vector_text(missedEstimates)}, SessionResult.LoggerClosed, ...
    numel(cleanupMessages), ...
    'VariableNames', {'RunID','OverallStatus','Pass','Completed','Partial', ...
    'DevelopmentOnly','ProductionEquivalent','CurrentPhase','StopReason', ...
    'DurationSeconds','ErrorIdentifier','SessionOutputDir','SourceReady', ...
    'SpatialHash','BaselineConfigHash', ...
    'TrialBaselineConfigHash','FeedbackLatencyPercentile', ...
    'FeedbackLatencyConfiguredPercentileMs','FeedbackLatencyMsP95', ...
    'SkippedFirstSample','SkippedLastSample','SkippedSampleCount', ...
    'FirstTrialSample','LastTrialSample','FirstValidMeasureWindowEndSample', ...
    'FirstFeedbackUpdateWindowEndSample','NFlipRequests', ...
    'NCompletedFlips','NMissedFlips','FlipMissedEstimates', ...
    'LoggerClosed','CleanupMessageCount'});
writetable(T, csvPath);

end

function value = local_field(S, fieldName, defaultValue)
value = defaultValue;
if isstruct(S) && isscalar(S) && isfield(S, fieldName) && ...
        ~isempty(S.(fieldName))
    value = S.(fieldName);
end
end

function value = local_nested_numeric(S, path, defaultValue)
value = defaultValue;
cursor = S;
for iPath = 1:numel(path)
    if ~isstruct(cursor) || ~isscalar(cursor) || ...
            ~isfield(cursor, path{iPath})
        return;
    end
    cursor = cursor.(path{iPath});
end
if isnumeric(cursor) && isscalar(cursor) && isreal(cursor)
    value = double(cursor);
end
end

function value = local_nested_text(S, path, defaultValue)
value = local_nested(S, path, defaultValue);
if ~(ischar(value) || isstring(value))
    value = defaultValue;
else
    value = char(value);
end
end

function value = local_nested(S, path, defaultValue)
value = defaultValue;
cursor = S;
for iPath = 1:numel(path)
    if ~isstruct(cursor) || ~isscalar(cursor) || ...
            ~isfield(cursor, path{iPath})
        return;
    end
    cursor = cursor.(path{iPath});
end
value = cursor;
end

function value = local_numeric_vector_text(values)
if isempty(values)
    value = '';
else
    value = strjoin(arrayfun(@(item) sprintf('%.17g', item), ...
        values(:)', 'UniformOutput', false), ';');
end
end
